recipe: "regression/v1"

# Specifies the target column for regression.
target_col: "Age"

# Sets the primary metric to use to evaluate model performance for regression.
primary_metric: "root_mean_squared_error"

steps:
  # Specifies the dataset to use for model development
  ingest: {{INGEST_CONFIG}}
  split:
    # Adjust the train/validation/test split ratios below
    split_ratios: [0.75, 0.125, 0.125]

  transform:
    using: "custom"
    transformer_method: "transformer_fn"

  train:
    # Specify that we are using a custom estimator method defined in train.py
    estimator_method: "estimator_fn"

    # Choose the estimator and its parameters here
    estimator: "LinearRegression"
    estimator_params:
      fit_intercept: true

    # Uncomment below to switch between other estimators
    # estimator: "RandomForestRegressor"
    # estimator_params:
    #   n_estimators: 100
    #   max_depth: 10
    #   random_state: 42

    # estimator: "GradientBoostingRegressor"
    # estimator_params:
    #   n_estimators: 200
    #   learning_rate: 0.1
    #   max_depth: 5
    
    # estimator: "SVR"
    # estimator_params:
    #   kernel: "linear"
    #   C: 1.0
    #   epsilon: 0.1

    # estimator: "DecisionTreeRegressor"
    # estimator_params:
    #   max_depth: 8
    #   min_samples_split: 5
    #   random_state: 42

  evaluate:
    validation_criteria:
      - metric: root_mean_squared_error
        threshold: 10.0

  register:
    allow_non_validated_model: True
