recipe: "regression/v1"

# Specifies the target column for regression.
target_col: "Age"

# Sets the primary metric to use to evaluate model performance for regression.
primary_metric: "root_mean_squared_error"

steps:
  # Specifies the dataset to use for model development
  ingest: {{INGEST_CONFIG}}
  split:
    # Adjust the train/validation/test split ratios below
    split_ratios: [0.75, 0.125, 0.125]

  transform:
    using: "custom"
    transformer_method: "transformer_fn"

  train:
    estimator_method: "estimator_fn"

  evaluate:
    # Sets performance thresholds for the model.
    validation_criteria:
      - metric: "r2_score"
        threshold: 0.8

  register:
    allow_non_validated_model: True
